### ISSUE TITLE
async-listen and UDP

### ISSUE THREAD

**Issue by sirxyzzy** [tailhook/async-listen#2]
I found this general statement in the async-listen codebase, the statement is echoed in the async book

    /// The wrapper works for `TcpListener` and `UdpListener` and returns
    /// the same `ByteStream` structure on both of them. This helps working
    /// with both kinds of sockets in a uniform way.

but I cannot find an example of using UDP, and UdpListener doesn't seem to be a thing, or at least I cannot find it! 

7 | use async_std::net::UdpListener;
  |     ^^^^^^^^^^^^^^^^-----------
  |     |               |
  |     |               help: a similar name exists in the module: `TcpListener`
  |     no `UdpListener` in `net`

Not only that but this code revolves around streams and my understanding is that UpdSocket is streamless.

Is async-listen really intended to efficiently handle Udp, or would I be better just leveraging lower level primitives?

**Comment by tailhook** [comment]
Oh, sorry, that's typo. It's `UnixListener`.

**Comment by tailhook** [comment]
> Is async-listen really intended to efficiently handle Udp, or would I be better just leveraging lower level primitives?

I don't think there is anything like this crate does that should be done for UDP (when there are no connections/sessions).

**Comment by sirxyzzy** [comment]
Thanks, not a problem, just confusion on my part
